Parallelize package tests
Signed-off-by: Christopher Grote <cmgrote@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,27 +8,50 @@ on:
   workflow_dispatch:
 
 jobs:
-  live-test:
+  build:
     runs-on: ubuntu-latest
-    name: "Integration"
+    name: "Build"
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
           java-version: 17
           distribution: temurin
-      - name: Integration tests
-        run: ./gradlew -PintegrationTests integration-tests:test
-        env:
-          ATLAN_BASE_URL: ${{ secrets.ATLAN_BASE_URL }}
-          ATLAN_API_KEY: ${{ secrets.ATLAN_API_KEY }}
-          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
-      - if: success() || failure()
+      - name: Compile
+        run: ./gradlew assemble shadowJar test
+      - name: Upload build artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: integration-logs
-          path: integration-tests/*.log
-  list-tests:
+          name: build-artifacts
+          path: |
+            integration-tests/build/classes/java/test/com/atlan/java/sdk/*.class
+            samples/packages/**/build/classes/kotlin/test/**/*.class
+  live-test:
+    needs: build
+    runs-on: ubuntu-latest
+    name: "Integration"
+    steps:
+      - uses: actions/checkout@v4
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-artifacts
+      - uses: actions/setup-java@v4
+        with:
+          java-version: 17
+          distribution: temurin
+      # - name: Integration tests
+      #   run: ./gradlew -PintegrationTests integration-tests:test
+      #   env:
+      #     ATLAN_BASE_URL: ${{ secrets.ATLAN_BASE_URL }}
+      #     ATLAN_API_KEY: ${{ secrets.ATLAN_API_KEY }}
+      #     NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
+      # - if: success() || failure()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: integration-logs
+      #     path: integration-tests/*.log
+  list-packages:
     runs-on: ubuntu-latest
     outputs:
       tests: ${{ steps.test-directories.outputs.tests }}
@@ -40,12 +63,14 @@ jobs:
           json_dirs=$(echo "${dirs[@]}" | jq -R -c 'split(" ")[:-1]')
           echo "tests=$json_dirs" >> $GITHUB_OUTPUT
   package-test:
-    needs: [list-tests]
+    needs:
+      - build
+      - list-packages
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        tests: ${{ fromJson(needs.list-tests.outputs.tests) }}
+        tests: ${{fromJson(needs.list-packages.outputs.tests)}}
     concurrency:
       group: ${{ matrix.tests }}
     name: "Packages"
@@ -53,6 +78,10 @@ jobs:
       - name: Free disk space
         uses: jlumbroso/free-disk-space@main
       - uses: actions/checkout@v4
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-artifacts
       - uses: actions/setup-java@v4
         with:
           java-version: 17
